### ISSUE TITLE
Error when running example scripts

### ISSUE THREAD

**Issue by hunbssfy** [llvm/mlir-npcomp#249]
Hi,

I am trying to run example scripts under `frontends/pytorch/examples` but I got two kinds of errors:

1. When I am running scripts using `capture_function`, I got:
![image](https://user-images.githubusercontent.com/6930027/125265451-70328e80-e337-11eb-84ec-027ff9b162c3.png)
the same error occurs when I run `cos_e2e.py, div_inplace_e2e.py, mm_e2e.py, mul_maximum_e2e.py, tanh_out_e2e.py`. Could someone tell me how to generate these op definitions and where to put them?

2. Running `torchscript_**_e2e.py` scripts gives me:
![image](https://user-images.githubusercontent.com/6930027/125266034-f9e25c00-e337-11eb-80ab-b0244b198cbf.png)

I am still learning the code so this might be a trivial question or maybe I just missed some steps? 
I went through all the build steps in README, I successfully ran tools/torchscrip_e2e_test.sh. I installed iree backend using pip.

**Comment by cathyzhyi** [comment]
Hey Maxi, you didn't miss any steps. 
For the first error, the short answer is that `aten.cos.out` is not supported yet. In order to support this, we need to update [torch_ods_gen.py](https://github.com/llvm/mlir-npcomp/blob/89d4931324589bf75ed088e98888ff21fe7cd41e/frontends/pytorch/python/torch_mlir_utils/codegen/torch_ods_gen.py#L401) and run `build_tools/update_torch_ods.sh` to generate the ods and lower this op in [TorchToLinalg](https://github.com/llvm/mlir-npcomp/blob/main/lib/Conversion/TorchToLinalg/TorchToLinalg.cpp)
For the second error, I can reproduce on my end but I am not sure what's the problem either. Sry!

**Comment by hunbssfy** [comment]
@cathyzhyi 
Hello Cathy,
Thanks for the reply! Is there any code submission similar to this kind of operator support that I can take a look at? Just want to get to know the whole lowering pass :)

**Comment by cathyzhyi** [comment]
Hey Maxi,  I can't find a good example of one single PR containing all the supports for one operator but you could use `aten::relu` as an example. Running `build_tools/update_torch_ods.sh` generates a file called `JITOperatorRegistryDump.txt` which contains all the operators with schema. You can find `aten::relu` and `aten::cos.out` in there.  After that, you could try to follow example of `aten::relu` and `AtenReluOp` in the codebase. Please let me know if you have any issues.

**Comment by hunbssfy** [comment]
@cathyzhyi 
Hello Cathy,

1. What is your current status and plan for supporting the common deep learning models? For example, Resnet 50. I see that there is a Resnet18 test case (torchscript e2e test) but it fails during the lowering phase (I am using IREE backend). And I see that silva is working on supporting the Resnet model here: https://github.com/llvm/mlir-npcomp/pull/212
2. Are you considering merging into the IREE project as one of its frontends in the future? It would be great because currently IREE already has Tensorflow frontend.

Thanks!

**Comment by stellaraccident** [comment]
Sean and Cathy can comment on their roadmap for supporting more models -- it is being actively worked on.

Regarding (2) - I am working this month on the python deployment machinery so that both npcomp and iree can be easily installed and the intent is that this will allow npcomp to use iree as a backend directly by regular users. It may take some iterations to get right as these are complicated dependencies but I expect this to start to become usable for folks within the next few months. IREE is hoping that the npcomp project can use it out of the box as an out of tree backend without the iree team needing to maintain an in tree PyTorch frontend itself.

**Comment by hunbssfy** [comment]
Great to know that, looking forward to it becomes more usable!

**Comment by cathyzhyi** [comment]
> What is your current status and plan for supporting the common deep learning models? For example, Resnet 50. I see that there is a Resnet18 test case (torchscript e2e test) but it fails during the lowering phase (I am using IREE backend). And I see that silva is working on supporting the Resnet model here: Progress on lowering ResNet #212

yea, we are working on making Resnet18 work which is one of the targets in the [Q3 roadmap](https://github.com/llvm/mlir-npcomp/blob/main/docs/roadmaps/2021Q3.md). Most of the recent PRs are relevant to this item.

**Comment by hunbssfy** [comment]
Right! I'll keep an eye on the progress :)

**Comment by silvasean** [comment]
FWIW, the .out variants are likely best handled in ReduceOpVariants. They can all be systematically handled there.

**Comment by dan-garvey** [comment]
@hunbssfy btw resnet_18 to iree now works, just edit the  frontends/pytorch/examples/ script and set iree as backend.

**Comment by hunbssfy** [comment]
> @hunbssfy btw resnet_18 to iree now works, just edit the frontends/pytorch/examples/ script and set iree as backend.

Yeah, I did the same modification and it works :)
