### ISSUE TITLE
Question about AdjustCallingConventionsPass

### ISSUE THREAD

**Issue by hunbssfy** [llvm/mlir-npcomp#291]
Basically, this pass changes calling conventions for FuncOp/CallOp/ReturnOp. And In the pass description, it says this pass "Adjusts the calling conventions of functions in the module, with the aim of preparing them for backends and further lowering passes."
Is there a standard calling convention of functions for backends and this standard is the aim of this conversion? If there is, where is it defined?

Also, I have questions about the reason behind the way it changes these ops.
Particularly for the following IR rewrite:
```
builtin.func @forward(%arg0: !torch.tensor {torch.type_bound = !torch.vtensor<[?,?,?,?],f32>}) -> !torch.tensor {
...
}
```
is changed to:
``` 
builtin.func @forward(%arg0: !torch.vtensor<[?,?,?,?],f32>) -> !torch.tensor {
    %0 = torch.tensor_static_info_cast %arg0 : !torch.vtensor<[?,?,?,?],f32> to !torch.vtensor
    %1 = torch.copy.to_tensor %0 : !torch.tensor
...
}
```

1. In function signature, non-value-semantic tensor type is changed to value-semantic tensor type. (`!torch.tensor {torch.type_bound = !torch.vtensor<...>, xtype>}` is changed to `!torch.vtensor<...>, xtype.`) Why do we need this change to remove this attribute? And why can't this be done when TorchScript program is imported? I see that in `IValueImporter::importCompilationUnit`, user annotations are parsed and `torch.type_bound` attribute is assigned.

2. `torch.tensor_static_info_cast` op is added to remove type and shape Infos from `!torch.vtensor` type. why do we need to do that? Could someone elaborate on what does `torch.static_info_cast` do? From what I have gathered, it can add or remove shape and type information from an operation, but what is special about this operation? 

3. Why add another `torch.copy.to_tensor` operation? If we have changed to value-semantic tensors, why change back?

**Comment by hunbssfy** [comment]
@silvasean Thanks for the explanation! 
So the whole point of this pass is adjusting the FuncOp/CallOp/ReturnOp calling convention, is that right? So we are to only change these parts of the IR and not meddle with the rest.

For example, in the FunOp signatures, when non-value semantic tensors with `type_bound` attribute are changed to value semantic tensors with type modifiers, it is because we need to make it more suitable for backend passes (they only accept value semantic tensor?). And because of this change, the following two lines: `torch.tensor_static_info_cast` and `torch.copy.to_tensor`, are here just to drop the type modifiers we just added to %arg0 and convert it back to its original non-value semantic tensor type in order not to mess with the rest part of the IR?

About `torch.tensor_static_info_cast`: you mentioned that it can be used to hint us we are not executing any runtime code, could you elaborate on this? Do you mean that if we see this operation in the IR, then this is not runtime code?

**Comment by silvasean** [comment]
Yes, it is just for adjusting calling conventions -- it doesn't change the internal code of the module, only the external calling conventions. Practically, right now IREE only accepts the MLIR builtin "tensor" type, so converting to value semantic tensors is necessary (and we bubble that up to users, because we need to make sure that users are not relying on non-value semantic tensors -- it's easy to write a program that does).


`torch.tensor_static_info_cast` only adjusts the static type. It's not a "hint". For example, if you have an op that returns `!torch.vtensor<[256],f32>` and you pass that value to an op that (for whatever reason) only accepts `!torch.vtensor<[?],f32>`, then to make the IR statically valid we need to insert a `torch.tensor_static_info_cast`. There are a number of situations like that, where we just need the same value, but with a different static type. By having only one op that does that, we make our IR representation more orthogonal and various types of bugs.

**Comment by hunbssfy** [comment]
Thanks, Sean, I got a rough understanding of this pass. I think I'll keep looking at later passes to get a better understanding.
